using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.RussStation.Economy;

[GenerateTypedNameReferences]
public sealed partial class BalanceCartridgeUiFragment : BoxContainer
{
    public BalanceCartridgeUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
    }

    public void UpdateState(int balance)
    {
        BalanceLabel.Text = balance.ToString();
    }
}
