using Content.Shared.RussStation.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.RussStation.Economy;

[GenerateTypedNameReferences]
public sealed partial class BalanceCartridgeUiFragment : BoxContainer
{
    public event Action? OnMuteToggled;

    private readonly Button _muteButton;
    private readonly BoxContainer _transactionList;

    public BalanceCartridgeUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;

        // Built in code to avoid XAML name-scope issues on fragment recreation.
        _muteButton = new Button
        {
            ToggleMode = true,
            Text = Loc.GetString("balance-cartridge-mute"),
            StyleClasses = { "OpenBoth" },
        };
        _muteButton.OnPressed += _ => OnMuteToggled?.Invoke();

        var muteRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 8, 0, 0),
        };
        muteRow.AddChild(_muteButton);

        var txHeader = new Label
        {
            Text = Loc.GetString("balance-cartridge-tx-header"),
            StyleClasses = { "LabelHeading" },
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 12, 0, 4),
        };

        _transactionList = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        var scroll = new ScrollContainer
        {
            VerticalExpand = true,
            HorizontalExpand = true,
        };
        scroll.AddChild(_transactionList);

        // The XAML BoxContainer is the second child (index 1) of the root.
        var content = (BoxContainer) GetChild(1);
        content.AddChild(muteRow);
        content.AddChild(txHeader);
        content.AddChild(scroll);
    }

    public void UpdateState(int balance, string accountSuffix, bool paycheckMuted, List<TransactionRecord> transactions, bool hasId)
    {
        _muteButton.Visible = hasId;

        if (!hasId)
        {
            BalanceLabel.Text = "-";
            AccountLabel.Text = Loc.GetString("balance-cartridge-no-id");
            _transactionList.RemoveAllChildren();
            return;
        }

        BalanceLabel.Text = balance.ToString();
        AccountLabel.Text = string.IsNullOrEmpty(accountSuffix)
            ? ""
            : Loc.GetString("balance-cartridge-account-suffix", ("suffix", accountSuffix));

        _muteButton.Pressed = paycheckMuted;
        _muteButton.Text = Loc.GetString(paycheckMuted
            ? "balance-cartridge-unmute"
            : "balance-cartridge-mute");

        _transactionList.RemoveAllChildren();

        if (transactions.Count == 0)
        {
            _transactionList.AddChild(new Label
            {
                Text = Loc.GetString("balance-cartridge-no-transactions"),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Center,
            });
            return;
        }

        // Show newest first.
        for (var i = transactions.Count - 1; i >= 0; i--)
        {
            var tx = transactions[i];
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var sign = tx.Amount >= 0 ? "+" : "";
            row.AddChild(new Label
            {
                Text = $"{sign}{tx.Amount}",
                StyleClasses = { tx.Amount >= 0 ? "LabelKeyValueStatValue" : "LabelSubText" },
                MinWidth = 60,
            });
            row.AddChild(new Label
            {
                Text = tx.Description,
                StyleClasses = { "LabelSubText" },
                HorizontalExpand = true,
            });

            _transactionList.AddChild(row);
        }
    }
}
