using Content.Shared.RussStation.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.RussStation.Economy;

[GenerateTypedNameReferences]
public sealed partial class BalanceCartridgeUiFragment : BoxContainer
{
    public event Action? OnMuteToggled;

    public BalanceCartridgeUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;

        MuteButton.OnPressed += _ => OnMuteToggled?.Invoke();
    }

    public void UpdateState(int balance, string accountSuffix, bool paycheckMuted, List<TransactionRecord> transactions)
    {
        BalanceLabel.Text = balance.ToString();
        AccountLabel.Text = string.IsNullOrEmpty(accountSuffix)
            ? ""
            : Loc.GetString("balance-cartridge-account-suffix", ("suffix", accountSuffix));

        MuteButton.Pressed = paycheckMuted;
        MuteButton.Text = Loc.GetString(paycheckMuted
            ? "balance-cartridge-unmute"
            : "balance-cartridge-mute");

        TransactionList.RemoveAllChildren();

        if (transactions.Count == 0)
        {
            TransactionList.AddChild(new Label
            {
                Text = Loc.GetString("balance-cartridge-no-transactions"),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Center,
            });
            return;
        }

        // Show newest first.
        for (var i = transactions.Count - 1; i >= 0; i--)
        {
            var tx = transactions[i];
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var sign = tx.Amount >= 0 ? "+" : "";
            row.AddChild(new Label
            {
                Text = $"{sign}{tx.Amount}",
                StyleClasses = { tx.Amount >= 0 ? "LabelKeyValueStatValue" : "LabelSubText" },
                MinWidth = 60,
            });
            row.AddChild(new Label
            {
                Text = tx.Description,
                StyleClasses = { "LabelSubText" },
                HorizontalExpand = true,
            });

            TransactionList.AddChild(row);
        }
    }
}
