using System.Globalization;
using Content.Shared.FixedPoint;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.RussStation.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.RussStation.MedicalScanner;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerReagentControl : BoxContainer
{
    private readonly IEntityManager _entityManager;
    private readonly IPrototypeManager _prototypes;

    public HealthAnalyzerReagentControl()
    {
        RobustXamlLoader.Load(this);

        var deps = IoCManager.Instance!;
        _entityManager = deps.Resolve<IEntityManager>();
        _prototypes = deps.Resolve<IPrototypeManager>();
    }

    public void Populate(HealthAnalyzerReagentState state)
    {
        PopulateHeader(state);
        PopulateGroups(state);
    }

    private static string FormatAmount(FixedPoint2 value)
        => value.Float().ToString("0.#", CultureInfo.InvariantCulture);

    private static string TitleCase(string value)
        => CultureInfo.CurrentCulture.TextInfo.ToTitleCase(value);

    private void PopulateHeader(HealthAnalyzerReagentState state)
    {
        var target = _entityManager.GetEntity(state.Target);

        if (_entityManager.EntityExists(target))
            SpriteView.SetEntity(target);

        SpriteView.Visible = state.Active;
        NoDataTex.Visible = !state.Active;

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(state.TargetName);
        NameLabel.SetMessage(name);

        if (_entityManager.TryGetComponent<HumanoidProfileComponent>(target, out var humanoid))
        {
            SpeciesLabel.Text = Loc.GetString(_prototypes.Index(humanoid.Species).Name);
            SpeciesLabel.Visible = true;
        }
        else
        {
            SpeciesLabel.Visible = false;
        }

        ScanModeLabel.Text = Loc.GetString(state.Active
            ? "health-analyzer-window-scan-mode-active"
            : "health-analyzer-window-scan-mode-inactive");
        ScanModeLabel.FontColorOverride = state.Active ? Color.Green : Color.Red;
    }

    private void PopulateGroups(HealthAnalyzerReagentState state)
    {
        GroupContainer.RemoveAllChildren();

        if (state.Groups.Count == 0)
        {
            GroupContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-reagent-empty"),
                HorizontalAlignment = Control.HAlignment.Left,
            });
            return;
        }

        foreach (var group in state.Groups)
        {
            var box = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                SeparationOverride = 2,
            };

            box.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-reagent-group-header",
                    ("label", TitleCase(group.Label)),
                    ("volume", FormatAmount(group.Volume)),
                    ("max", FormatAmount(group.MaxVolume))),
                StyleClasses = { "LabelSubText" },
            });

            if (group.Reagents.Count == 0)
            {
                box.AddChild(new Label
                {
                    Text = Loc.GetString("health-analyzer-reagent-group-empty"),
                    Margin = new Robust.Shared.Maths.Thickness(8, 0, 0, 0),
                });
            }
            else
            {
                foreach (var reagent in group.Reagents)
                {
                    var line = new BoxContainer
                    {
                        Orientation = LayoutOrientation.Horizontal,
                        Margin = new Robust.Shared.Maths.Thickness(8, 0, 0, 0),
                        HorizontalExpand = true,
                    };

                    line.AddChild(new PanelContainer
                    {
                        MinSize = new System.Numerics.Vector2(10, 10),
                        SetSize = new System.Numerics.Vector2(10, 10),
                        VerticalAlignment = Control.VAlignment.Center,
                        PanelOverride = new StyleBoxFlat
                        {
                            BackgroundColor = reagent.Color,
                        },
                    });

                    string locKey;
                    Color? color;
                    if (reagent.Overdose)
                    {
                        locKey = "health-analyzer-reagent-line-overdose";
                        color = Color.OrangeRed;
                    }
                    else if (reagent.Underdose)
                    {
                        locKey = "health-analyzer-reagent-line-underdose";
                        color = Color.SkyBlue;
                    }
                    else
                    {
                        locKey = "health-analyzer-reagent-line";
                        color = null;
                    }

                    line.AddChild(new Label
                    {
                        Text = Loc.GetString(locKey,
                            ("name", TitleCase(reagent.ReagentName)),
                            ("quantity", FormatAmount(reagent.Quantity))),
                        Margin = new Robust.Shared.Maths.Thickness(6, 0, 0, 0),
                        FontColorOverride = color,
                    });

                    box.AddChild(line);
                }
            }

            GroupContainer.AddChild(box);
        }
    }
}
