using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Content.Shared.RussStation.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.RussStation.MedicalScanner;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerTabbedWindow : FancyWindow
{
    private readonly IEntityManager _entityManager;
    private readonly IPlayerManager _player;
    private readonly IPrototypeManager _prototypes;

    public HealthAnalyzerTabbedWindow()
    {
        RobustXamlLoader.Load(this);

        var deps = IoCManager.Instance!;
        _entityManager = deps.Resolve<IEntityManager>();
        _player = deps.Resolve<IPlayerManager>();
        _prototypes = deps.Resolve<IPrototypeManager>();

        Tabs.SetTabTitle((int) HealthAnalyzerTab.Health, Loc.GetString("health-analyzer-tab-health"));
        Tabs.SetTabTitle((int) HealthAnalyzerTab.Reagents, Loc.GetString("health-analyzer-tab-reagents"));
        Tabs.SetTabTitle((int) HealthAnalyzerTab.Wounds, Loc.GetString("health-analyzer-tab-wounds"));
    }

    public void PopulateHealth(HealthAnalyzerScannedUserMessage msg)
    {
        // Upstream's control requires DamageableComponent and leaves its stale patient
        // block visible when given an empty state, producing a duplicate "no data" line.
        // For non-mob scans we swap in our own header-only placeholder that mirrors the
        // Wounds tab layout (sprite + name + species + scan mode + empty label).
        var hasTarget = msg.State.TargetEntity != default;
        HealthAnalyzer.Visible = hasTarget;
        HealthEmptyView.Visible = !hasTarget;

        if (hasTarget)
            HealthAnalyzer.Populate(msg.State);
        else
            PopulateEmptyHeader(msg.State);

        Wounds.Populate(msg.State);
    }

    private void PopulateEmptyHeader(HealthAnalyzerUiState state)
    {
        var target = _entityManager.GetEntity(state.TargetEntity);
        var active = state.ScanMode == true;

        if (target != null && _entityManager.EntityExists(target))
            HealthEmptySpriteView.SetEntity(target);

        HealthEmptySpriteView.Visible = active;
        HealthEmptyNoDataTex.Visible = !active;

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(target != null && _entityManager.HasComponent<MetaDataComponent>(target.Value)
            ? Identity.Name(target.Value, _entityManager, _player.LocalEntity)
            : Loc.GetString("health-analyzer-window-entity-unknown-text"));
        HealthEmptyNameLabel.SetMessage(name);

        if (target != null && _entityManager.TryGetComponent<HumanoidProfileComponent>(target, out var humanoid))
        {
            HealthEmptySpeciesLabel.Text = Loc.GetString(_prototypes.Index(humanoid.Species).Name);
            HealthEmptySpeciesLabel.Visible = true;
        }
        else
        {
            HealthEmptySpeciesLabel.Visible = false;
        }

        HealthEmptyScanModeLabel.Text = Loc.GetString(active
            ? "health-analyzer-window-scan-mode-active"
            : "health-analyzer-window-scan-mode-inactive");
        HealthEmptyScanModeLabel.FontColorOverride = active ? Color.Green : Color.Red;
    }

    public void PopulateReagents(HealthAnalyzerReagentState state)
    {
        Reagents.Populate(state);
    }

    public void SelectTab(HealthAnalyzerTab tab)
    {
        Tabs.CurrentTab = (int) tab;
    }
}
