using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.RussStation.MedicalScanner;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWoundControl : BoxContainer
{
    private readonly IEntityManager _entityManager;
    private readonly IPlayerManager _player;

    public HealthAnalyzerWoundControl()
    {
        RobustXamlLoader.Load(this);

        var deps = IoCManager.Instance!;
        _entityManager = deps.Resolve<IEntityManager>();
        _player = deps.Resolve<IPlayerManager>();
    }

    public void Populate(HealthAnalyzerUiState state)
    {
        var target = _entityManager.GetEntity(state.TargetEntity);
        var active = state.ScanMode == true;
        var name = target != null && _entityManager.HasComponent<MetaDataComponent>(target.Value)
            ? Identity.Name(target.Value, _entityManager, _player.LocalEntity)
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        Header.Populate(target, name, active);
        PopulateWounds(state.Wounds);
    }

    private void PopulateWounds(IReadOnlyList<Content.Shared.RussStation.Wounds.WoundDisplayInfo>? wounds)
    {
        WoundList.RemoveAllChildren();

        var hasWounds = wounds is { Count: > 0 };
        EmptyLabel.Visible = !hasWounds;
        WoundList.Visible = hasWounds;

        if (!hasWounds)
            return;

        foreach (var wound in wounds!)
        {
            var color = wound.Tier switch
            {
                >= 3 => Color.Red,
                2 => Color.Orange,
                _ => Color.Yellow,
            };

            WoundList.AddChild(new RichTextLabel
            {
                Text = Loc.GetString(wound.LocKey),
                Margin = new Thickness(0, 4),
                MaxWidth = 300,
                Modulate = color,
            });
        }
    }
}
