using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.RussStation.MedicalScanner;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerPatientHeader : BoxContainer
{
    private readonly IEntityManager _entityManager;
    private readonly IPrototypeManager _prototypes;

    public HealthAnalyzerPatientHeader()
    {
        RobustXamlLoader.Load(this);

        var deps = IoCManager.Instance!;
        _entityManager = deps.Resolve<IEntityManager>();
        _prototypes = deps.Resolve<IPrototypeManager>();
    }

    public void Populate(EntityUid? target, string name, bool active)
    {
        if (target is { } t && _entityManager.EntityExists(t))
            SpriteView.SetEntity(t);

        SpriteView.Visible = active;
        NoDataTex.Visible = !active;

        var message = new FormattedMessage();
        message.PushColor(Color.White);
        message.AddText(name);
        NameLabel.SetMessage(message);

        if (target is { } th && _entityManager.TryGetComponent<HumanoidProfileComponent>(th, out var humanoid))
        {
            SpeciesLabel.Text = Loc.GetString(_prototypes.Index(humanoid.Species).Name);
            SpeciesLabel.Visible = true;
        }
        else
        {
            SpeciesLabel.Visible = false;
        }

        ScanModeLabel.Text = Loc.GetString(active
            ? "health-analyzer-window-scan-mode-active"
            : "health-analyzer-window-scan-mode-inactive");
        ScanModeLabel.FontColorOverride = active ? Color.Green : Color.Red;
    }
}
