using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.RussStation.MedicalScanner;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWoundControl : BoxContainer
{
    private readonly IEntityManager _entityManager;
    private readonly IPlayerManager _player;
    private readonly IPrototypeManager _prototypes;

    public HealthAnalyzerWoundControl()
    {
        RobustXamlLoader.Load(this);

        var deps = IoCManager.Instance!;
        _entityManager = deps.Resolve<IEntityManager>();
        _player = deps.Resolve<IPlayerManager>();
        _prototypes = deps.Resolve<IPrototypeManager>();
    }

    public void Populate(HealthAnalyzerUiState state)
    {
        PopulateHeader(state);
        PopulateWounds(state.Wounds);
    }

    private void PopulateHeader(HealthAnalyzerUiState state)
    {
        var target = _entityManager.GetEntity(state.TargetEntity);
        var active = state.ScanMode == true;

        if (target != null && _entityManager.EntityExists(target))
            SpriteView.SetEntity(target);

        SpriteView.Visible = active;
        NoDataTex.Visible = !active;

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(target != null && _entityManager.HasComponent<MetaDataComponent>(target.Value)
            ? Identity.Name(target.Value, _entityManager, _player.LocalEntity)
            : Loc.GetString("health-analyzer-window-entity-unknown-text"));
        NameLabel.SetMessage(name);

        if (target != null && _entityManager.TryGetComponent<HumanoidProfileComponent>(target, out var humanoid))
        {
            SpeciesLabel.Text = Loc.GetString(_prototypes.Index(humanoid.Species).Name);
            SpeciesLabel.Visible = true;
        }
        else
        {
            SpeciesLabel.Visible = false;
        }

        ScanModeLabel.Text = Loc.GetString(active
            ? "health-analyzer-window-scan-mode-active"
            : "health-analyzer-window-scan-mode-inactive");
        ScanModeLabel.FontColorOverride = active ? Color.Green : Color.Red;
    }

    private void PopulateWounds(IReadOnlyList<Content.Shared.RussStation.Wounds.WoundDisplayInfo>? wounds)
    {
        WoundList.RemoveAllChildren();

        var hasWounds = wounds is { Count: > 0 };
        EmptyLabel.Visible = !hasWounds;
        WoundList.Visible = hasWounds;

        if (!hasWounds)
            return;

        foreach (var wound in wounds!)
        {
            var color = wound.Tier switch
            {
                >= 3 => Color.Red,
                2 => Color.Orange,
                _ => Color.Yellow,
            };

            WoundList.AddChild(new RichTextLabel
            {
                Text = Loc.GetString(wound.LocKey),
                Margin = new Thickness(0, 4),
                MaxWidth = 300,
                Modulate = color,
            });
        }
    }
}
