using Content.Client.UserInterface.Controls;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Content.Shared.RussStation.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.RussStation.MedicalScanner;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerTabbedWindow : FancyWindow
{
    private readonly IEntityManager _entityManager;
    private readonly IPlayerManager _player;

    public HealthAnalyzerTabbedWindow()
    {
        RobustXamlLoader.Load(this);

        var deps = IoCManager.Instance!;
        _entityManager = deps.Resolve<IEntityManager>();
        _player = deps.Resolve<IPlayerManager>();

        Tabs.SetTabTitle((int) HealthAnalyzerTab.Health, Loc.GetString("health-analyzer-tab-health"));
        Tabs.SetTabTitle((int) HealthAnalyzerTab.Reagents, Loc.GetString("health-analyzer-tab-reagents"));
        Tabs.SetTabTitle((int) HealthAnalyzerTab.Wounds, Loc.GetString("health-analyzer-tab-wounds"));
    }

    public void PopulateHealth(HealthAnalyzerScannedUserMessage msg)
    {
        // Upstream's control requires DamageableComponent and leaves its stale patient
        // block visible when given an empty state, producing a duplicate "no data" line.
        // For non-mob scans we swap in a header-only placeholder that mirrors the other tabs.
        var hasTarget = msg.State.TargetEntity != default;
        HealthAnalyzer.Visible = hasTarget;
        HealthEmptyView.Visible = !hasTarget;

        if (hasTarget)
            HealthAnalyzer.Populate(msg.State);
        else
            PopulateEmptyHeader(msg.State);

        Wounds.Populate(msg.State);
    }

    private void PopulateEmptyHeader(HealthAnalyzerUiState state)
    {
        var target = _entityManager.GetEntity(state.TargetEntity);
        var active = state.ScanMode == true;
        var name = target != null && _entityManager.HasComponent<MetaDataComponent>(target.Value)
            ? Identity.Name(target.Value, _entityManager, _player.LocalEntity)
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        HealthEmptyHeader.Populate(target, name, active);
    }

    public void PopulateReagents(HealthAnalyzerReagentState state)
    {
        Reagents.Populate(state);
    }

    public void SelectTab(HealthAnalyzerTab tab)
    {
        Tabs.CurrentTab = (int) tab;
    }
}
