using System.Globalization;
using Content.Shared.FixedPoint;
using Content.Shared.RussStation.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.RussStation.MedicalScanner;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerReagentControl : BoxContainer
{
    private readonly IEntityManager _entityManager;

    public HealthAnalyzerReagentControl()
    {
        RobustXamlLoader.Load(this);

        _entityManager = IoCManager.Instance!.Resolve<IEntityManager>();
    }

    public void Populate(HealthAnalyzerReagentState state)
    {
        Header.Populate(_entityManager.GetEntity(state.Target), state.TargetName, state.Active);
        PopulateGroups(state);
    }

    private static string FormatAmount(FixedPoint2 value)
        => value.Float().ToString("0.#", CultureInfo.InvariantCulture);

    private static string TitleCase(string value)
        => CultureInfo.CurrentCulture.TextInfo.ToTitleCase(value);

    private void PopulateGroups(HealthAnalyzerReagentState state)
    {
        GroupContainer.RemoveAllChildren();

        if (state.Groups.Count == 0)
        {
            GroupContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-reagent-empty"),
                HorizontalAlignment = Control.HAlignment.Left,
            });
            return;
        }

        foreach (var group in state.Groups)
        {
            var box = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                SeparationOverride = 2,
            };

            box.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-reagent-group-header",
                    ("label", TitleCase(group.Label)),
                    ("volume", FormatAmount(group.Volume)),
                    ("max", FormatAmount(group.MaxVolume))),
                StyleClasses = { "LabelSubText" },
            });

            if (group.Reagents.Count == 0)
            {
                box.AddChild(new Label
                {
                    Text = Loc.GetString("health-analyzer-reagent-group-empty"),
                    Margin = new Robust.Shared.Maths.Thickness(8, 0, 0, 0),
                });
            }
            else
            {
                foreach (var reagent in group.Reagents)
                {
                    var line = new BoxContainer
                    {
                        Orientation = LayoutOrientation.Horizontal,
                        Margin = new Robust.Shared.Maths.Thickness(8, 0, 0, 0),
                        HorizontalExpand = true,
                    };

                    line.AddChild(new PanelContainer
                    {
                        MinSize = new System.Numerics.Vector2(10, 10),
                        SetSize = new System.Numerics.Vector2(10, 10),
                        VerticalAlignment = Control.VAlignment.Center,
                        PanelOverride = new StyleBoxFlat
                        {
                            BackgroundColor = reagent.Color,
                        },
                    });

                    string locKey;
                    Color? color;
                    if (reagent.Overdose)
                    {
                        locKey = "health-analyzer-reagent-line-overdose";
                        color = Color.OrangeRed;
                    }
                    else if (reagent.Underdose)
                    {
                        locKey = "health-analyzer-reagent-line-underdose";
                        color = Color.SkyBlue;
                    }
                    else
                    {
                        locKey = "health-analyzer-reagent-line";
                        color = null;
                    }

                    line.AddChild(new Label
                    {
                        Text = Loc.GetString(locKey,
                            ("name", TitleCase(reagent.ReagentName)),
                            ("quantity", FormatAmount(reagent.Quantity))),
                        Margin = new Robust.Shared.Maths.Thickness(6, 0, 0, 0),
                        FontColorOverride = color,
                    });

                    box.AddChild(line);
                }
            }

            GroupContainer.AddChild(box);
        }
    }
}
