//HONK START - font customization + hover tooltip accessibility options
using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.Stylesheets.Fonts;
//HONK END
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
//HONK START
using Robust.Shared.Configuration;
//HONK END

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AccessibilityTab : Control
{
    public AccessibilityTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(CCVars.ChatEnableColorName, EnableColorNameCheckBox);
        Control.AddOptionCheckBox(CCVars.AccessibilityColorblindFriendly, ColorblindFriendlyCheckBox);
        Control.AddOptionCheckBox(CCVars.ReducedMotion, ReducedMotionCheckBox);
        Control.AddOptionPercentSlider(CCVars.ScreenShakeIntensity, ScreenShakeIntensitySlider);
        Control.AddOptionPercentSlider(CCVars.ChatWindowOpacity, ChatWindowOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleTextOpacity, SpeechBubbleTextOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleSpeakerOpacity, SpeechBubbleSpeakerOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleBackgroundOpacity, SpeechBubbleBackgroundOpacitySlider);
        Control.AddOptionCheckBox(CCVars.ChatAutoFillHighlights, AutoFillHighlightsCheckBox);
        Control.AddOptionColorSlider(CCVars.ChatHighlightsColor, HighlightsColorSlider);

        //HONK START
        Control.AddOptionCheckBox(CCVars.HoverTooltipEnabled, HoverTooltipEnabledCheckBox);
        Control.AddOption(new OptionSliderFloatCVar(
            Control,
            IoCManager.Resolve<IConfigurationManager>(),
            CCVars.HoverTooltipDelay,
            HoverTooltipDelaySlider,
            0f,
            20f,
            0.1f,
            (_, value) => $"{value * 0.1f:F1}s"));

        // Font customization
        var cfg = IoCManager.Resolve<IConfigurationManager>();
        var stylesheetMan = IoCManager.Resolve<IStylesheetManager>() as StylesheetManager;
        var fontManager = stylesheetMan?.FontManager;

        if (fontManager != null)
        {
            Control.AddOptionDropDown(CCVars.UIFontFamily, FontFamilyDropDown, BuildFontOptions(fontManager));

            Control.AddOption(new OptionSliderIntCVar(
                Control,
                cfg,
                CCVars.UIFontSize,
                FontSizeSlider,
                8,
                24,
                (_, value) => $"{value}px"));

            OpenFontsFolderButton.OnPressed += _ => fontManager.OpenUserFontsFolder();
            RescanFontsButton.OnPressed += _ =>
            {
                fontManager.RescanUserFonts();
                RefreshFontDropDown(fontManager, cfg);
            };
        }
        //HONK END

        Control.AddOptionCheckBox(CCVars.AccessibilityClientCensorNudity, CensorNudityCheckBox);

        Control.Initialize();
    }

    // HONK START - Font customization helpers
    private static List<OptionDropDownCVar<string>.ValueOption> BuildFontOptions(FontCustomizationManager fontManager)
    {
        return fontManager.AvailableFonts.Values
            .OrderBy(f => f.Name == "NotoSans" ? 0 : f.IsUserFont ? 2 : 1)
            .ThenBy(f => f.Name)
            .Select(f =>
            {
                string label;
                if (f.Name == "NotoSans")
                    label = $"{f.Name} (default)";
                else if (f.IsUserFont)
                    label = $"{f.Name} (custom)";
                else
                    label = f.Name;
                return new OptionDropDownCVar<string>.ValueOption(f.Name, label);
            })
            .ToList();
    }

    private void RefreshFontDropDown(FontCustomizationManager fontManager, IConfigurationManager cfg)
    {
        var button = FontFamilyDropDown.Button;
        var currentValue = cfg.GetCVar(CCVars.UIFontFamily);

        button.Clear();

        var options = BuildFontOptions(fontManager);
        for (var i = 0; i < options.Count; i++)
        {
            button.AddItem(options[i].Label, i);
            button.SetItemMetadata(button.GetIdx(i), options[i].Key);

            if (options[i].Key == currentValue)
                button.SelectId(i);
        }
    }
    // HONK END
}

