using Robust.Client.AutoGenerated;
//HONK START - inline collapsible filter panel instead of upstream dropdown
using Content.Client.RussStation.UI;
//HONK END
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Actions.Windows;

[GenerateTypedNameReferences]
public sealed partial class ActionsWindow : DefaultWindow
{
    public const string StyleClassActionSearchBox = "actionSearchBox";

    //HONK START - swapped upstream MultiselectOptionButton for HonkFilterPanel
    public HonkFilterPanel<Filters> FilterButton { get; private set; }
    //HONK END

    /// <summary>
    /// Whether the displayed actions or search filter needs updating.
    /// </summary>
    public bool UpdateNeeded;

    public ActionsWindow()
    {
        RobustXamlLoader.Load(this);

        //HONK START - header sits inline in the search row; body drops under it when expanded
        FilterButton = new HonkFilterPanel<Filters>
        {
            Label = Loc.GetString("ui-actionmenu-filter-button")
        };
        SearchContainer.AddChild(FilterButton.Header);
        FilterContainer.AddChild(FilterButton.Body);
        //HONK END

        foreach (var filter in Enum.GetValues<Filters>())
        {
            FilterButton.AddItem(Loc.GetString($"ui-actionmenu-{filter.ToString().ToLower()}"), filter);
        }
    }

    public enum Filters
    {
        Enabled,
        Item,
        Innate,
        Instant,
        //HONK START - emote-as-action filter (#579); trailing comma added to Targeted above
        Targeted,
        Emote,
        //HONK END
    }
}
