using System.Linq;
using Content.Shared.Light.Components;
using Content.Shared.RussStation.Light;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.RussStation.Light;

[GenerateTypedNameReferences]
public sealed partial class LightReplacerRecyclerWindow : DefaultWindow
{
    private static readonly Thickness RowIndent = new(16, 0, 0, 0);

    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IComponentFactory _compFactory = default!;

    public event Action<EntProtoId>? OnExtract;
    public event Action<EntProtoId>? OnPrint;

    // Collapse state keyed by (list, subsection) so state survives state-push rebuilds.
    private readonly Dictionary<string, bool> _subCollapsed = new();

    public LightReplacerRecyclerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(LightReplacerRecyclerBoundUserInterfaceState state)
    {
        PointsLabel.Text = Loc.GetString("light-replacer-recycler-window-points-value",
            ("points", state.Points),
            ("cost", state.PrintCost));

        RebuildStored(state.Stored);
        RebuildPrint(state.Printable, state.Points, state.PrintCost);
    }

    private void RebuildStored(List<LightReplacerStoredBulb> stored)
    {
        StoredContainer.RemoveAllChildren();

        var bulbs = new List<LightReplacerStoredBulb>();
        var tubes = new List<LightReplacerStoredBulb>();
        foreach (var entry in stored)
        {
            if (LookupBulbType(entry.ProtoId) == LightBulbType.Tube)
                tubes.Add(entry);
            else
                bulbs.Add(entry);
        }

        AddCollapsibleSubsection(
            key: "stored-bulbs",
            parent: StoredContainer,
            header: Loc.GetString("light-replacer-recycler-window-subheader-bulbs"),
            entryCount: bulbs.Sum(b => b.Count),
            populate: body =>
            {
                foreach (var entry in bulbs)
                    body.AddChild(BuildStoredRow(entry));
            });

        AddCollapsibleSubsection(
            key: "stored-tubes",
            parent: StoredContainer,
            header: Loc.GetString("light-replacer-recycler-window-subheader-tubes"),
            entryCount: tubes.Sum(t => t.Count),
            populate: body =>
            {
                foreach (var entry in tubes)
                    body.AddChild(BuildStoredRow(entry));
            });

        StoredEmptyLabel.Visible = stored.Count == 0;
    }

    private Control BuildStoredRow(LightReplacerStoredBulb entry)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6,
            Margin = RowIndent,
        };

        var name = _protoManager.TryIndex<EntityPrototype>(entry.ProtoId, out var proto)
            ? proto.Name
            : entry.ProtoId.Id;

        row.AddChild(new Label
        {
            Text = name,
            HorizontalExpand = true,
        });
        row.AddChild(new Label
        {
            Text = Loc.GetString("light-replacer-recycler-window-stored-count", ("count", entry.Count)),
        });

        var extract = new Button
        {
            Text = Loc.GetString("light-replacer-recycler-window-extract"),
        };
        var protoId = entry.ProtoId;
        extract.OnPressed += _ => OnExtract?.Invoke(protoId);
        row.AddChild(extract);

        return row;
    }

    private void RebuildPrint(List<EntProtoId> printable, int points, int printCost)
    {
        PrintContainer.RemoveAllChildren();

        var bulbs = new List<EntProtoId>();
        var tubes = new List<EntProtoId>();
        foreach (var protoId in printable)
        {
            if (LookupBulbType(protoId) == LightBulbType.Tube)
                tubes.Add(protoId);
            else
                bulbs.Add(protoId);
        }

        var canAfford = points >= printCost;

        AddCollapsibleSubsection(
            key: "print-bulbs",
            parent: PrintContainer,
            header: Loc.GetString("light-replacer-recycler-window-subheader-bulbs"),
            entryCount: bulbs.Count,
            populate: body =>
            {
                foreach (var protoId in bulbs)
                    body.AddChild(BuildPrintRow(protoId, canAfford, printCost));
            });

        AddCollapsibleSubsection(
            key: "print-tubes",
            parent: PrintContainer,
            header: Loc.GetString("light-replacer-recycler-window-subheader-tubes"),
            entryCount: tubes.Count,
            populate: body =>
            {
                foreach (var protoId in tubes)
                    body.AddChild(BuildPrintRow(protoId, canAfford, printCost));
            });
    }

    private Control BuildPrintRow(EntProtoId protoId, bool canAfford, int printCost)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6,
            Margin = RowIndent,
        };

        var name = _protoManager.TryIndex<EntityPrototype>(protoId, out var proto)
            ? proto.Name
            : protoId.Id;

        row.AddChild(new Label
        {
            Text = name,
            HorizontalExpand = true,
        });

        var print = new Button
        {
            Text = Loc.GetString("light-replacer-recycler-window-print", ("cost", printCost)),
            Disabled = !canAfford,
        };
        var captured = protoId;
        print.OnPressed += _ => OnPrint?.Invoke(captured);
        row.AddChild(print);

        return row;
    }

    // Adds a collapsible subsection with a toggle button header. Skips entirely when entryCount is 0.
    private void AddCollapsibleSubsection(string key, BoxContainer parent, string header, int entryCount, Action<BoxContainer> populate)
    {
        if (entryCount == 0)
            return;

        var collapsed = _subCollapsed.GetValueOrDefault(key, true);

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 2,
            Visible = !collapsed,
        };

        var button = new Button
        {
            HorizontalExpand = true,
            TextAlign = Label.AlignMode.Left,
            Text = FormatSubHeader(header, entryCount, collapsed),
        };
        button.OnPressed += _ =>
        {
            var now = !_subCollapsed.GetValueOrDefault(key, true);
            _subCollapsed[key] = now;
            body.Visible = !now;
            button.Text = FormatSubHeader(header, entryCount, now);
        };

        populate(body);

        parent.AddChild(button);
        parent.AddChild(body);
    }

    private static string FormatSubHeader(string header, int entryCount, bool collapsed)
    {
        var arrow = collapsed ? "▸" : "▾";
        return $"{arrow} {header} ({entryCount})";
    }

    private LightBulbType LookupBulbType(EntProtoId protoId)
    {
        if (_protoManager.TryIndex<EntityPrototype>(protoId, out var proto)
            && proto.TryGetComponent<LightBulbComponent>(out var bulb, _compFactory))
            return bulb.Type;
        return LightBulbType.Bulb;
    }
}
