using Content.Client.RussStation.Botany;
using Content.Shared.RussStation.Botany;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.RussStation.Botany.UI;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    public PlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);

        Tabs.SetTabTitle(0, Loc.GetString("plant-analyzer-tab-stats"));
        Tabs.SetTabTitle(1, Loc.GetString("plant-analyzer-tab-traits"));
        Tabs.SetTabTitle(2, Loc.GetString("plant-analyzer-tab-chemicals"));
    }

    public void Populate(PlantAnalyzerScannedUserMessage msg)
    {
        var state = msg.State;

        Title = Loc.GetString("plant-analyzer-window-title");
        PlantNameLabel.Text = state.SeedName;

        PopulateStats(state);
        PopulateTraits(state);
        PopulateChemicals(state);
    }

    private void PopulateStats(PlantAnalyzerUiState state)
    {
        StatsBox.Children.Clear();

        StatsBox.AddChild(SectionHeader(Loc.GetString("plant-analyzer-section-basic")));
        var basic = MakeGrid();
        AddStatRow(basic, "plant-analyzer-stat-potency", state.Potency.ToString("F1"));
        AddStatRow(basic, "plant-analyzer-stat-yield", state.Yield.ToString());
        AddStatRow(basic, "plant-analyzer-stat-production", state.Production.ToString("F1"));
        AddStatRow(basic, "plant-analyzer-stat-maturation", state.Maturation.ToString("F1"));
        AddStatRow(basic, "plant-analyzer-stat-lifespan", state.Lifespan.ToString("F1"));
        AddStatRow(basic, "plant-analyzer-stat-endurance", state.Endurance.ToString("F1"));
        AddStatRow(basic, "plant-analyzer-stat-growth-stages", state.GrowthStages.ToString());
        AddStatRow(basic, "plant-analyzer-stat-harvest-repeat", state.HarvestRepeat);
        StatsBox.AddChild(basic);

        StatsBox.AddChild(SectionHeader(Loc.GetString("plant-analyzer-section-advanced")));
        var adv = MakeGrid();
        AddStatRow(adv, "plant-analyzer-stat-nutrient-consumption", state.NutrientConsumption.ToString("F2"));
        AddStatRow(adv, "plant-analyzer-stat-water-consumption", state.WaterConsumption.ToString("F2"));
        AddStatRow(adv, "plant-analyzer-stat-weed-tolerance", state.WeedTolerance.ToString("F1"));
        AddStatRow(adv, "plant-analyzer-stat-pest-tolerance", state.PestTolerance.ToString("F1"));
        AddStatRow(adv, "plant-analyzer-stat-toxins-tolerance", state.ToxinsTolerance.ToString("F1"));
        AddStatRow(adv, "plant-analyzer-stat-ideal-light", state.IdealLight.ToString("F1"));
        AddStatRow(adv, "plant-analyzer-stat-light-tolerance", state.LightTolerance.ToString("F1"));
        AddStatRow(adv, "plant-analyzer-stat-ideal-heat", state.IdealHeat.ToString("F1"));
        AddStatRow(adv, "plant-analyzer-stat-heat-tolerance", state.HeatTolerance.ToString("F1"));
        AddStatRow(adv, "plant-analyzer-stat-low-pressure-tolerance", state.LowPressureTolerance.ToString("F1"));
        AddStatRow(adv, "plant-analyzer-stat-high-pressure-tolerance", state.HighPressureTolerance.ToString("F1"));
        StatsBox.AddChild(adv);
    }

    private void PopulateTraits(PlantAnalyzerUiState state)
    {
        TraitsBox.Children.Clear();

        if (state.Traits.Count == 0)
        {
            TraitsBox.AddChild(new Label
            {
                Text = Loc.GetString("plant-analyzer-traits-none"),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(BotanyClientConstants.PlantAnalyzerUITraitsNoneLabelMarginLeft, BotanyClientConstants.PlantAnalyzerUITraitsNoneLabelMarginTop, BotanyClientConstants.PlantAnalyzerUITraitsNoneLabelMarginRight, BotanyClientConstants.PlantAnalyzerUITraitsNoneLabelMarginBottom),
            });
            return;
        }

        foreach (var trait in state.Traits)
        {
            TraitsBox.AddChild(new Label { Text = $"• {trait}" });
        }
    }

    private void PopulateChemicals(PlantAnalyzerUiState state)
    {
        ChemicalsBox.Children.Clear();

        if (state.Chemicals.Count > 0)
        {
            ChemicalsBox.AddChild(SectionHeader(Loc.GetString("plant-analyzer-section-chemicals")));
            var grid = MakeGrid();
            foreach (var (name, amount) in state.Chemicals)
                AddRow(grid, name, amount.ToString());
            ChemicalsBox.AddChild(grid);
        }

        if (state.ConsumeGases.Count > 0)
        {
            ChemicalsBox.AddChild(SectionHeader(Loc.GetString("plant-analyzer-section-consume-gases")));
            var grid = MakeGrid();
            foreach (var (name, rate) in state.ConsumeGases)
                AddRow(grid, name, rate.ToString("F3"));
            ChemicalsBox.AddChild(grid);
        }

        if (state.ExudeGases.Count > 0)
        {
            ChemicalsBox.AddChild(SectionHeader(Loc.GetString("plant-analyzer-section-exude-gases")));
            var grid = MakeGrid();
            foreach (var (name, rate) in state.ExudeGases)
                AddRow(grid, name, rate.ToString("F3"));
            ChemicalsBox.AddChild(grid);
        }

        if (state.Chemicals.Count == 0 && state.ConsumeGases.Count == 0 && state.ExudeGases.Count == 0)
        {
            ChemicalsBox.AddChild(new Label
            {
                Text = Loc.GetString("plant-analyzer-chemicals-none"),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(BotanyClientConstants.PlantAnalyzerUITraitsNoneLabelMarginLeft, BotanyClientConstants.PlantAnalyzerUITraitsNoneLabelMarginTop, BotanyClientConstants.PlantAnalyzerUITraitsNoneLabelMarginRight, BotanyClientConstants.PlantAnalyzerUITraitsNoneLabelMarginBottom),
            });
        }
    }

    private static Label SectionHeader(string text)
    {
        return new Label
        {
            Text = text,
            StyleClasses = { "LabelSubText" },
            Margin = new Thickness(0, 4, 0, 0),
        };
    }

    private static GridContainer MakeGrid()
    {
        return new GridContainer
        {
            Columns = 2,
            HorizontalExpand = true,
        };
    }

    private static void AddStatRow(GridContainer grid, string locKey, string value)
    {
        AddRow(grid, Loc.GetString(locKey), value);
    }

    private static void AddRow(GridContainer grid, string label, string value)
    {
        grid.AddChild(new Label
        {
            Text = label,
            HorizontalExpand = true,
        });
        grid.AddChild(new Label
        {
            Text = value,
            HorizontalAlignment = HAlignment.Right,
            Margin = new Thickness(BotanyClientConstants.PlantAnalyzerUIStatsValueLabelMarginLeft, BotanyClientConstants.PlantAnalyzerUIStatsValueLabelMarginTop, BotanyClientConstants.PlantAnalyzerUIStatsValueLabelMarginRight, BotanyClientConstants.PlantAnalyzerUIStatsValueLabelMarginBottom),
        });
    }
}
