using System.Linq;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.RussStation.ActionBar;

[GenerateTypedNameReferences]
public sealed partial class ActionBarPresetsWindow : DefaultWindow
{
    private readonly ActionBarPresetStore _store;
    private readonly IConfigurationManager _cfg;
    private readonly Action<ActionBarPreset> _apply;
    private readonly Func<ActionBarPreset> _capture;
    private readonly Action _resetToDefaults;
    private readonly Func<string> _getCharacterName;

    public ActionBarPresetsWindow(
        ActionBarPresetStore store,
        IConfigurationManager cfg,
        Func<ActionBarPreset> capture,
        Action<ActionBarPreset> apply,
        Action resetToDefaults,
        Func<string> getCharacterName)
    {
        RobustXamlLoader.Load(this);
        _store = store;
        _cfg = cfg;
        _capture = capture;
        _apply = apply;
        _resetToDefaults = resetToDefaults;
        _getCharacterName = getCharacterName;

        LockToggle.Pressed = _cfg.GetCVar(CCVars.HonkActionBarLock);
        LockToggle.OnToggled += a => _cfg.SetCVar(CCVars.HonkActionBarLock, a.Pressed);
        _cfg.OnValueChanged(CCVars.HonkActionBarLock, OnLockChanged);

        SaveAsButton.OnPressed += _ => DoSave();
        ResetButton.OnPressed += _ => DoReset();
        _store.Changed += Refresh;

        Refresh();
    }

    private void OnLockChanged(bool value) => LockToggle.Pressed = value;

    protected override void Dispose(bool disposing)
    {
        // Unsub on dispose, not Close. Close just hides the window — the customization
        // controller may reopen the same instance later, and unsubbing on Close left the
        // UI stale on the second open (delete/save would mutate the store but Refresh
        // never ran). Tying the unsub to Dispose keeps the subscription alive across
        // hide/show cycles and only releases when the window is genuinely going away.
        if (disposing)
        {
            _store.Changed -= Refresh;
            _cfg.UnsubValueChanged(CCVars.HonkActionBarLock, OnLockChanged);
        }
        base.Dispose(disposing);
    }

    private void DoSave()
    {
        var name = SaveNameEdit.Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
            return;
        var preset = _capture();
        preset.Name = name;
        _store.Save(preset);
        SaveNameEdit.Text = string.Empty;
    }

    private void DoReset()
    {
        // Repopulates slots from the player's known actions and snaps the bar position
        // back to the default anchor. Size/spacing/label/alpha live in Options → Misc
        // and stay untouched; the lock toggle is also preserved.
        _resetToDefaults();
    }

    private void Refresh()
    {
        PresetList.RemoveAllChildren();
        // Show only presets that belong to the active character (or character-agnostic
        // ones from before the scoping change), so a Vox-specific preset doesn't tempt
        // a Human player to load it and lose half their slots to invalid emote ids.
        var character = _getCharacterName();
        var visible = _store.Presets
            .Where(p => string.IsNullOrEmpty(p.CharacterName)
                || string.Equals(p.CharacterName, character, StringComparison.Ordinal))
            .ToList();
        EmptyLabel.Visible = visible.Count == 0;
        foreach (var preset in visible)
        {
            PresetList.AddChild(BuildRow(preset));
        }
    }

    private BoxContainer BuildRow(ActionBarPreset preset)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 4,
        };
        row.AddChild(new Label { Text = preset.Name, HorizontalExpand = true });
        var loadBtn = new Button { Text = Loc.GetString("ui-actionbar-presets-load") };
        loadBtn.OnPressed += _ => _apply(preset);
        var deleteBtn = new Button { Text = Loc.GetString("ui-actionbar-presets-delete") };
        deleteBtn.OnPressed += _ => _store.Delete(preset.Name);
        row.AddChild(loadBtn);
        row.AddChild(deleteBtn);
        return row;
    }
}
