using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.RussStation.ActionBar;

[GenerateTypedNameReferences]
public sealed partial class ActionBarPresetsWindow : DefaultWindow
{
    private readonly ActionBarPresetStore _store;
    private readonly IConfigurationManager _cfg;
    private readonly Action<ActionBarPreset> _apply;
    private readonly Func<ActionBarPreset> _capture;
    private readonly Action _resetToDefaults;

    public ActionBarPresetsWindow(
        ActionBarPresetStore store,
        IConfigurationManager cfg,
        Func<ActionBarPreset> capture,
        Action<ActionBarPreset> apply,
        Action resetToDefaults)
    {
        RobustXamlLoader.Load(this);
        _store = store;
        _cfg = cfg;
        _capture = capture;
        _apply = apply;
        _resetToDefaults = resetToDefaults;

        LockToggle.Pressed = _cfg.GetCVar(CCVars.HonkActionBarLock);
        LockToggle.OnToggled += a => _cfg.SetCVar(CCVars.HonkActionBarLock, a.Pressed);
        _cfg.OnValueChanged(CCVars.HonkActionBarLock, OnLockChanged);

        SaveAsButton.OnPressed += _ => DoSave();
        ResetButton.OnPressed += _ => DoReset();
        _store.Changed += Refresh;

        Refresh();
    }

    private void OnLockChanged(bool value) => LockToggle.Pressed = value;

    public override void Close()
    {
        _store.Changed -= Refresh;
        _cfg.UnsubValueChanged(CCVars.HonkActionBarLock, OnLockChanged);
        base.Close();
    }

    private void DoSave()
    {
        var name = SaveNameEdit.Text.Trim();
        if (string.IsNullOrWhiteSpace(name))
            return;
        var preset = _capture();
        preset.Name = name;
        _store.Save(preset);
        SaveNameEdit.Text = string.Empty;
    }

    private void DoReset()
    {
        // Wipes layout/position CVars and clears slot contents. The lock toggle stays
        // wherever the player had it — resetting "the layout" shouldn't unlock a bar
        // they explicitly chose to keep frozen.
        _resetToDefaults();
    }

    private void Refresh()
    {
        PresetList.RemoveAllChildren();
        var presets = _store.Presets;
        EmptyLabel.Visible = presets.Count == 0;
        foreach (var preset in presets)
        {
            PresetList.AddChild(BuildRow(preset));
        }
    }

    private BoxContainer BuildRow(ActionBarPreset preset)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 4,
        };
        row.AddChild(new Label { Text = preset.Name, HorizontalExpand = true });
        var loadBtn = new Button { Text = Loc.GetString("ui-actionbar-presets-load") };
        loadBtn.OnPressed += _ => _apply(preset);
        var deleteBtn = new Button { Text = Loc.GetString("ui-actionbar-presets-delete") };
        deleteBtn.OnPressed += _ => _store.Delete(preset.Name);
        row.AddChild(loadBtn);
        row.AddChild(deleteBtn);
        return row;
    }
}
