using Content.Shared.RussStation.Messenger;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.RussStation.Messenger;

[GenerateTypedNameReferences]
public sealed partial class MessengerCartridgeUiFragment : BoxContainer
{
    public event Action<NetEntity>? OnContactSelected;
    public event Action<NetEntity, string>? OnSendMessage;
    public event Action? OnBackPressed;
    public event Action? OnMuteToggled;

    private readonly BoxContainer _contactList;
    private readonly BoxContainer _chatView;
    private readonly BoxContainer _messageList;
    private readonly LineEdit _messageInput;
    private readonly Button _sendButton;
    private readonly Button _backButton;
    private readonly Button _muteButton;
    private readonly Label _addressLabel;

    private NetEntity? _activeTarget;

    public MessengerCartridgeUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;

        var content = (BoxContainer) GetChild(1);

        // Contact list view.
        _contactList = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        var contactScroll = new ScrollContainer
        {
            VerticalExpand = true,
            HorizontalExpand = true,
        };
        contactScroll.AddChild(_contactList);

        // Chat view (hidden by default).
        _chatView = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
            Visible = false,
        };

        _backButton = new Button
        {
            Text = Loc.GetString("messenger-back"),
            StyleClasses = { "OpenBoth" },
            HorizontalAlignment = HAlignment.Left,
            Margin = new Thickness(0, 0, 0, 4),
        };
        _backButton.OnPressed += _ => OnBackPressed?.Invoke();

        _messageList = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        var messageScroll = new ScrollContainer
        {
            VerticalExpand = true,
            HorizontalExpand = true,
        };
        messageScroll.AddChild(_messageList);

        var inputRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 4, 0, 0),
        };

        _messageInput = new LineEdit
        {
            HorizontalExpand = true,
            PlaceHolder = Loc.GetString("messenger-placeholder"),
        };
        _messageInput.OnTextEntered += _ => SendCurrentMessage();

        _sendButton = new Button
        {
            Text = Loc.GetString("messenger-send"),
            StyleClasses = { "OpenBoth" },
            Margin = new Thickness(4, 0, 0, 0),
        };
        _sendButton.OnPressed += _ => SendCurrentMessage();

        inputRow.AddChild(_messageInput);
        inputRow.AddChild(_sendButton);

        _chatView.AddChild(_backButton);
        _chatView.AddChild(messageScroll);
        _chatView.AddChild(inputRow);

        _muteButton = new Button
        {
            ToggleMode = true,
            Text = Loc.GetString("messenger-mute"),
            StyleClasses = { "OpenBoth" },
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 4, 0, 4),
        };
        _muteButton.OnPressed += _ => OnMuteToggled?.Invoke();

        _addressLabel = new Label
        {
            StyleClasses = { "LabelSubText" },
            HorizontalAlignment = HAlignment.Right,
            Margin = new Thickness(0, 2, 4, 0),
        };

        var body = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            VerticalExpand = true,
            HorizontalExpand = true,
        };
        body.AddChild(_muteButton);
        body.AddChild(contactScroll);
        body.AddChild(_chatView);

        content.AddChild(body);
        content.AddChild(_addressLabel);
    }

    public void UpdateState(MessengerUiState state)
    {
        _addressLabel.Text = state.Address;

        if (state.ActiveConversation != null)
        {
            ShowChatView(state);
        }
        else
        {
            ShowContactList(state);
        }
    }

    private void ShowContactList(MessengerUiState state)
    {
        _contactList.Visible = true;
        _chatView.Visible = false;
        _muteButton.Visible = true;
        _activeTarget = null;

        _muteButton.Pressed = state.Muted;
        _muteButton.Text = Loc.GetString(state.Muted ? "messenger-unmute" : "messenger-mute");

        HeaderLabel.Text = Loc.GetString("messenger-program-name");

        _contactList.RemoveAllChildren();

        if (!state.HasId)
        {
            _contactList.AddChild(new Label
            {
                Text = Loc.GetString("messenger-no-id"),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Center,
            });

            if (state.Contacts.Count == 0)
                return;
        }

        if (state.Contacts.Count == 0)
        {
            _contactList.AddChild(new Label
            {
                Text = Loc.GetString("messenger-no-contacts"),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Center,
            });
            return;
        }

        foreach (var contact in state.Contacts)
        {
            var row = new Button
            {
                StyleClasses = { "OpenBoth" },
                HorizontalExpand = true,
                Margin = new Thickness(0, 1, 0, 1),
            };

            var rowContent = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var nameLabel = new Label
            {
                Text = contact.Name,
                HorizontalExpand = true,
            };

            var jobLabel = new Label
            {
                Text = contact.JobTitle,
                StyleClasses = { "LabelSubText" },
                Margin = new Thickness(8, 0, 0, 0),
            };

            rowContent.AddChild(nameLabel);
            rowContent.AddChild(jobLabel);

            if (contact.HasUnread)
            {
                var unreadDot = new Label
                {
                    Text = "*",
                    StyleClasses = { "LabelKeyValueStatValue" },
                    Margin = new Thickness(4, 0, 0, 0),
                };
                rowContent.AddChild(unreadDot);
            }

            row.AddChild(rowContent);

            var target = contact.Cartridge;
            row.OnPressed += _ => OnContactSelected?.Invoke(target);

            _contactList.AddChild(row);
        }
    }

    private void ShowChatView(MessengerUiState state)
    {
        _contactList.Visible = false;
        _chatView.Visible = true;
        _muteButton.Visible = false;
        _activeTarget = state.ActiveConversation;

        // Find the active contact.
        var contactName = "";
        var readOnly = false;
        foreach (var contact in state.Contacts)
        {
            if (contact.Cartridge == state.ActiveConversation)
            {
                contactName = contact.Name;
                readOnly = contact.ReadOnly;
                break;
            }
        }

        HeaderLabel.Text = contactName;

        var canSend = !readOnly && state.HasId;
        _messageInput.Visible = canSend;
        _sendButton.Visible = canSend;

        _messageList.RemoveAllChildren();

        if (state.Messages == null || state.Messages.Count == 0)
        {
            _messageList.AddChild(new Label
            {
                Text = Loc.GetString("messenger-no-messages"),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Center,
            });
            return;
        }

        foreach (var msg in state.Messages)
        {
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2, 0, 2),
            };

            var senderLabel = new Label
            {
                Text = msg.SenderName,
                StyleClasses = { msg.FromSelf ? "LabelKeyValueStatValue" : "LabelSubText" },
            };

            var textLabel = new Label
            {
                Text = msg.Text,
                HorizontalExpand = true,
            };

            row.AddChild(senderLabel);
            row.AddChild(textLabel);
            _messageList.AddChild(row);
        }
    }

    private void SendCurrentMessage()
    {
        if (_activeTarget == null)
            return;

        var text = _messageInput.Text.Trim();
        if (string.IsNullOrEmpty(text))
            return;

        OnSendMessage?.Invoke(_activeTarget.Value, text);
        _messageInput.Text = "";
    }
}
