using System.Linq;
using Content.Client.Resources;
using Content.Shared.Atmos;
using Content.Shared.Atmos.EntitySystems;
using Content.Shared.Atmos.Piping.Portable.Components;
using Content.Shared.Atmos.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Atmos.UI;

[GenerateTypedNameReferences]
public sealed partial class PortableScrubberWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IResourceCache _resCache = default!;

    private const string PartialCheckboxTexturePath = "/Textures/@RussStation/Interface/Nano/checkbox_partial.svg.96dpi.png";

    public event Action<Gas>? OnGasToggled;

    private readonly Dictionary<Gas, CheckBox> _gasChecks = new();
    private readonly Dictionary<Gas, string> _gasDisplayNames = new();
    private readonly List<CategorySection> _categories = new();
    private bool _suppressParentToggle;

    // Robust's CheckBox has no mixed-state support. We fake it by swapping the TextureRect's texture
    // to a diagonally-filled glyph whenever the category is partially selected, and by appending the
    // selected/total count to the parent label.
    private Texture? _partialCheckTexture;

    // Gas groupings for the filter list. Any gas not listed here falls into Exotic so newly-added
    // engine gases don't disappear from the UI.
    private static readonly (string LocKey, Gas[] Gases)[] CategoryLayout =
    {
        ("portable-scrubber-ui-filter-category-air", new[] { Gas.Oxygen, Gas.Nitrogen }),
        ("portable-scrubber-ui-filter-category-waste", new[] { Gas.CarbonDioxide, Gas.WaterVapor, Gas.NitrousOxide, Gas.Ammonia }),
        ("portable-scrubber-ui-filter-category-dangerous", new[] { Gas.Plasma, Gas.Tritium, Gas.Hydrogen, Gas.Frezon }),
    };

    public PortableScrubberWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _partialCheckTexture = _resCache.GetTexture(PartialCheckboxTexturePath);

        var atmosphereSystem = _entMan.System<SharedAtmosphereSystem>();

        foreach (var gas in Enum.GetValues<Gas>())
        {
            ProtoId<GasPrototype> gasProtoId = atmosphereSystem.GetGas(gas);
            var gasName = Loc.GetString(_prototypeManager.Index(gasProtoId).Name);

            var check = new CheckBox
            {
                Text = gasName,
                HorizontalExpand = true,
            };
            check.OnToggled += _ =>
            {
                OnGasToggled?.Invoke(gas);
                RefreshParentCheckboxes();
            };

            _gasChecks[gas] = check;
            _gasDisplayNames[gas] = gasName;
        }

        BuildCategories();
        SearchBar.OnTextChanged += _ => ApplyFilter();
    }

    private void BuildCategories()
    {
        var categorized = new HashSet<Gas>();

        foreach (var (locKey, gases) in CategoryLayout)
        {
            var resolved = gases.Where(g => _gasChecks.ContainsKey(g)).ToArray();
            if (resolved.Length == 0)
                continue;
            AddSection(Loc.GetString(locKey), resolved);
            foreach (var gas in resolved)
                categorized.Add(gas);
        }

        var exoticGases = Enum.GetValues<Gas>().Where(g => !categorized.Contains(g)).ToArray();
        if (exoticGases.Length > 0)
            AddSection(Loc.GetString("portable-scrubber-ui-filter-category-exotic"), exoticGases);
    }

    private void AddSection(string title, Gas[] gases)
    {
        var collapseButton = new Button
        {
            Text = "▸",
            MinSize = new System.Numerics.Vector2(22, 0),
        };

        var parentCheck = new CheckBox
        {
            Text = title,
            HorizontalExpand = true,
        };

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 4, 0, 0),
            SeparationOverride = 4,
        };
        header.AddChild(collapseButton);
        header.AddChild(parentCheck);

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(22, 0, 0, 0),
            SeparationOverride = 2,
        };

        foreach (var gas in gases)
            body.AddChild(_gasChecks[gas]);

        GasContainer.AddChild(header);
        GasContainer.AddChild(body);

        var section = new CategorySection(title, header, parentCheck, collapseButton, body, gases)
        {
            Collapsed = true,
        };
        body.Visible = false;
        _categories.Add(section);

        collapseButton.OnPressed += _ => ToggleCollapsed(section);
        parentCheck.OnToggled += args => OnParentToggled(section, args.Pressed);
    }

    private void ToggleCollapsed(CategorySection section)
    {
        section.Collapsed = !section.Collapsed;
        section.CollapseButton.Text = section.Collapsed ? "▸" : "▾";
        ApplyFilter();
    }

    private void OnParentToggled(CategorySection section, bool pressed)
    {
        // Ignore toggles that come from our own RefreshParentCheckboxes pass.
        if (_suppressParentToggle)
            return;

        foreach (var gas in section.Gases)
        {
            var check = _gasChecks[gas];
            if (check.Pressed != pressed)
            {
                check.Pressed = pressed;
                OnGasToggled?.Invoke(gas);
            }
        }
    }

    private void RefreshParentCheckboxes()
    {
        _suppressParentToggle = true;
        try
        {
            foreach (var section in _categories)
            {
                var selected = section.Gases.Count(g => _gasChecks[g].Pressed);
                var total = section.Gases.Count;
                var all = selected == total;
                var partial = selected > 0 && selected < total;

                section.ParentCheck.Pressed = all;
                section.ParentCheck.Text = partial
                    ? $"{section.Title} ({selected}/{total})"
                    : section.Title;
                // Swap the check-glyph texture to the diagonal-fill one for partial state. When all
                // or none, clear the override so the stylesheet resumes driving checked/unchecked.
                section.ParentCheck.TextureRect.Texture = partial ? _partialCheckTexture : null;
            }
        }
        finally
        {
            _suppressParentToggle = false;
        }
    }

    private void ApplyFilter()
    {
        var query = SearchBar.Text.Trim();
        var hasQuery = query.Length > 0;
        var anyVisible = false;

        foreach (var section in _categories)
        {
            var sectionHasMatch = false;
            foreach (var gas in section.Gases)
            {
                var match = !hasQuery
                    || _gasDisplayNames[gas].Contains(query, StringComparison.OrdinalIgnoreCase);
                _gasChecks[gas].Visible = match;
                sectionHasMatch |= match;
            }

            section.Header.Visible = sectionHasMatch;
            // Body is hidden when the section is collapsed or when nothing matches the search.
            // A search match auto-expands the section: the user asked to find something, so show it.
            section.Body.Visible = sectionHasMatch && (!section.Collapsed || hasQuery);
            anyVisible |= sectionHasMatch;
        }

        EmptyLabel.Visible = !anyVisible;
    }

    public void SetActive(bool active)
    {
        ToggleStatusButton.Pressed = active;
    }

    public void UpdateState(PortableScrubberBoundUserInterfaceState state)
    {
        ToggleStatusButton.Disabled = !state.Anchored;
        // An unanchored scrubber can't actually run, so force the switch to read "off" regardless
        // of what the server's Enabled flag says. Otherwise a freshly-spawned scrubber shows as on.
        ToggleStatusButton.Pressed = state.Anchored && state.Enabled;
        ToggleStatusButton.ToolTip = state.Anchored
            ? null
            : Loc.GetString("portable-scrubber-ui-not-anchored");

        foreach (var (gas, check) in _gasChecks)
            check.Pressed = state.FilterGases.Contains(gas);

        RefreshParentCheckboxes();

        var fraction = state.MaxPressure > 0f ? state.Pressure / state.MaxPressure : 0f;
        PressureBar.Value = Math.Clamp(fraction, 0f, 1f);
        PressureLabel.Text = Loc.GetString("portable-scrubber-ui-pressure-value",
            ("pressure", (int) state.Pressure),
            ("max", (int) state.MaxPressure),
            ("percent", (int) Math.Round(fraction * 100)));
    }

    private sealed class CategorySection
    {
        public string Title { get; }
        public BoxContainer Header { get; }
        public CheckBox ParentCheck { get; }
        public Button CollapseButton { get; }
        public BoxContainer Body { get; }
        public IReadOnlyList<Gas> Gases { get; }
        public bool Collapsed { get; set; }

        public CategorySection(string title, BoxContainer header, CheckBox parentCheck, Button collapseButton, BoxContainer body, IReadOnlyList<Gas> gases)
        {
            Title = title;
            Header = header;
            ParentCheck = parentCheck;
            CollapseButton = collapseButton;
            Body = body;
            Gases = gases;
        }
    }
}
