//HONK START
using System.Linq;
//HONK END
using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class GeneralStationRecordConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public Action<uint?>? OnKeySelected;

    public Action<StationRecordFilterType, string>? OnFiltersChanged;
    public Action<uint>? OnDeleted;

    private bool _isPopulating;

    public GeneralStationRecordConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        //HONK START - swap OptionButton/LineEdit/Search/Reset row for shared live-filter widget
        SearchBar.SetPlaceholder(Loc.GetString("general-station-record-for-filter-line-placeholder"));
        SearchBar.PopulateTypes(
            Enum.GetValues<StationRecordFilterType>().Select(t => ((int)t, GetTypeFilterLocals(t))),
            (int)StationRecordFilterType.Name);
        //HONK END

        RecordListing.OnItemSelected += args =>
        {
            if (_isPopulating || RecordListing[args.ItemIndex].Metadata is not uint cast)
                return;

            OnKeySelected?.Invoke(cast);
        };

        RecordListing.OnItemDeselected += _ =>
        {
            if (!_isPopulating)
                OnKeySelected?.Invoke(null);
        };

        //HONK START - single subscription covers both type and text changes
        SearchBar.OnFilterChanged += args => FilterListingOfRecords(args.Text);
        //HONK END
    }

    public void UpdateState(GeneralStationRecordConsoleState state)
    {
        //HONK START - shared search bar mirrors filter state
        if (state.Filter != null)
            SearchBar.ApplyFilterState((int)state.Filter.Type, state.Filter.Value);
        //HONK END

        if (state.RecordListing == null)
        {
            RecordListingStatus.Visible = true;
            RecordListing.Visible = false;
            RecordListingStatus.Text = Loc.GetString("general-station-record-console-empty-state");
            RecordContainer.Visible = false;
            RecordContainerStatus.Visible = false;
            return;
        }

        RecordListingStatus.Visible = false;
        RecordListing.Visible = true;
        RecordContainer.Visible = true;

        PopulateRecordListing(state.RecordListing!, state.SelectedKey);

        RecordContainerStatus.Visible = state.Record == null;

        if (state.Record != null)
        {
            RecordContainerStatus.Visible = state.SelectedKey == null;
            RecordContainerStatus.Text = state.SelectedKey == null
                ? Loc.GetString("general-station-record-console-no-record-found")
                : Loc.GetString("general-station-record-console-select-record-info");
            PopulateRecordContainer(state.Record, state.CanDeleteEntries, state.SelectedKey);
        }
        else
        {
            RecordContainer.RemoveAllChildren();
        }
    }
    private void PopulateRecordListing(Dictionary<uint, string> listing, uint? selected)
    {
        RecordListing.Clear();
        RecordListing.ClearSelected();

        _isPopulating = true;

        foreach (var (key, name) in listing)
        {
            var item = RecordListing.AddItem(name);
            item.Metadata = key;
            item.Selected = key == selected;
        }
        _isPopulating = false;

        RecordListing.SortItemsByText();
    }

    private void PopulateRecordContainer(GeneralStationRecord record, bool enableDelete, uint? id)
    {
        RecordContainer.RemoveAllChildren();
        var newRecord = new GeneralRecord(record, enableDelete, id, _prototypeManager);
        newRecord.OnDeletePressed = OnDeleted;

        RecordContainer.AddChild(newRecord);
    }

    private void FilterListingOfRecords(string text = "")
    {
        if (!_isPopulating)
        {
            //HONK START - SearchBar.SelectedTypeId replaces upstream _currentFilterType field
            OnFiltersChanged?.Invoke((StationRecordFilterType)SearchBar.SelectedTypeId, text);
            //HONK END
        }
    }

    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"general-station-record-{type.ToString().ToLower()}-filter");
    }

}
